### ISSUE TITLE
Coliru Share Link Life

### ISSUE THREAD

**Issue by saatvikshah** [StackedCrooked/coliru#7]
Hi, I'd like to start by thanking you for providing the functionality to run and share code snippets with minimal restrictions!  That said, I recently noticed that one of my earlier working links seems to have expired with an error indicating that the file is missing on Dropbox: https://coliru.stacked-crooked.com/a/7edcbcfe5f5a5916. <br>
Just wanted to clarify if there is some anticipated share link life?

**Comment by StackedCrooked** [comment]
There has been some data loss in the past caused by a non-recoverable
machine crash. It's likely that your code got lost in such an event. Sorry
about that :(

Btw, I plan to keep the data online forever, or at least for as long as I'm
online myself. So there's no real expiration policy or anything.


Francis

Op ma 4 mrt. 2019 om 01:39 schreef Saatvik Shah <notifications@github.com>:

**Comment by saatvikshah** [comment]
Thanks! Glad to hear that
